# Generated by Django 5.2.4 on 2026-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('enroll', models.IntegerField()),
                ('std', models.CharField()),
                ('sec', models.CharField()),
            ],
        ),
    ]
