# Generated by Django 5.2.4 on 2026-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('standard', models.IntegerField(max_length=100)),
                ('senroll', models.IntegerField(max_length=100)),
                ('mobno', models.IntegerField(max_length=12)),
                ('pmobno', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(max_length=100),
        ),
    ]
