# Generated by Django 5.2.4 on 2026-02-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_signup_alter_student_enroll_alter_student_rollno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='standard',
            new_name='sstd',
        ),
    ]
