# Generated by Django 5.2.4 on 2026-02-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0005_studentmark_alter_student_enroll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=150)),
                ('standard', models.CharField(max_length=20)),
                ('activity_type', models.CharField(choices=[('sports', 'Sports'), ('drawing', 'Drawing'), ('dance', 'Dance'), ('music', 'Music'), ('drama', 'Drama')], max_length=20)),
                ('sports_name', models.CharField(blank=True, choices=[('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton'), ('table_tennis', 'Table Tennis'), ('volleyball', 'Volleyball'), ('swimming', 'Swimming'), ('long_jump', 'Long Jump')], max_length=30, null=True)),
                ('activity_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
